export const tags = [
  '#VirtualProduction',
  '#UnrealEngine',
  '#CGI #Environments',
  '#Design #ICVFX',
  '#Productiondesign',
  '#MotionGraphics',
  '#VisualEffects',
  '#Setsupervision',
  '#RealtimeOverEverything',
  '#GameEngine #ArtDirection',
  '#Advertising #Movies',
  '#TVShows #Web',
  '#Metaverse',
  '#Web3 #Metahuman',
  '#AR #VR #MR',
  '#MixedMedia',
  '#Kreuzberg #Berlin',
  '#ReichenbergerStrasse125',
  '#WeirdCoffeePeople',
  '#PingPong',
  '#Vegan',
  '#VirtualProduction',
  '#UnrealEngine',
  '#CGI #Environments',
  '#Design #ICVFX',
  '#Productiondesign',
  '#MotionGraphics',
  '#VisualEffects',
  '#Setsupervision',
  '#RealtimeOverEverything',
  '#GameEngine #ArtDirection',
  '#Advertising #Movies',
  '#TVShows #Web',
  '#Metaverse',
  '#Web3 #Metahuman',
  '#AR #VR #MR',
  '#MixedMedia',
  '#Kreuzberg #Berlin',
  '#ReichenbergerStrasse125',
  '#WeirdCoffeePeople',
  '#PingPong',
  '#Vegan',
]
